### ISSUE TITLE
Possible issue when user converts to other market while bot is running

### ISSUE THREAD

**Issue by letsautom8** [whittlem/pycryptobot#107]
This is a bit of an edge case. 

Currently we are checking if previous action is BUY, we set last_action as BUY otherwise, it is a sell.
This can lead to a wrong state if user choses to manually convert (for example DOGE) fund to quote currency (i.e. USDT) (instead of doing it in trade). The last action would be buy but the fund is in USDT.

im thinking of the following rules:
1. if base currency has enough funds to do a sell, then last_action is BUY
2. if quote currency has enough funds to do a buy, then last_action is SELL

However what do we prioritise if both rules are satisfied? any thoughts?

**Comment by fepetoo** [comment]
hmm... that is an interesting problem..

for example i have BNB - USDT with bot running
bot bought BNB
my other take profit/stop loss got triggered, now i got usdt too

(sorry i don't know, how the buy/sell triggers are handled insude, so maybe this scenario cannot happen)
in case, 2 will be taken
buy signal will arise, bot will buy BNB... but how be the resistance/support/etc calculated then? the last buy.. but the previously bought hat completly different values there... i think it could be a little bit nightmare(ish) to implement this.. 

in case 1 will be taken
i assume, buy trigger will not rise
however sellatloss could be a problem here, because the bot will not know, what was the buy price... 

so i vote for 1... it looks for me safer solution

**Comment by whittlem** [comment]
There is another feature request logged in the Issues to be able to specify the start action with an argument or config setting. This should solve your problem right? The bot tries its best to determine the starting state based on funds but it would be useful to set the state in some cases. It sounds like this is what you need. I have a few things I want to sort out on the bot this evening but if I have time I'll add this as well.

**Comment by whittlem** [comment]
I added the --lastaction BUY and --lastaction SELL functionality. Can you confirm it resolved your issue?

**Comment by whittlem** [comment]
@letsautom8, did --lastaction resolve this?

**Comment by whittlem** [comment]
Closing as no response was given in 12 days.
