### ISSUE TITLE
Question: Why is Margin calculation different for Binance and Coinbase Pro

### ISSUE THREAD

**Issue by YannickDieter** [whittlem/pycryptobot#210]
Hi @edrickrenan @whittlem,

can you please explain why the margin calculation for binance and coinbase pro is different? For me this makes no sense.
In addition it gives also wrong margins (in case of binance) as visible in this screenshot:
![wrong_margin](https://user-images.githubusercontent.com/22544302/118894447-8a865800-b904-11eb-86e7-42ecd9107481.PNG)

Thanks,
Yannick

**Comment by YannickDieter** [comment]
We should add more unit tests using your simulation feature.

**Comment by marioK93** [comment]
Hi Yannick,

I put the calculations together, there is a difference for both because the data returned by the apis differs between the two exchanges so the calculations are different to take this into account

I believe the remaining issue lies with simulations only on binance and is being looked into

**Comment by whittlem** [comment]
This may be fixed now. Can you please confirm?

**Comment by whittlem** [comment]
No response in 15 days. Closing this.
