### ISSUE TITLE
sellupperpcnt not working correctly

### ISSUE THREAD

**Issue by t3ch9** [whittlem/pycryptobot#30]
I run the bot with the following command:

python pycryptobot.py --exchange binance --market ENJUSDT --granularity 1h --sim fast --verbose 0 --live 0 --smartswitch 1 --sellatloss 0 --sellupperpcnt 9

The sellupperpcnt is supposed to force sell when the margin reaches an upper limit of 9%, but based on the log, the sell happens when profit is less than 9%.  (multiple examples attached)

![image](https://user-images.githubusercontent.com/29530317/113963904-77a64100-97f8-11eb-92dd-29ad4390174a.png)

![image](https://user-images.githubusercontent.com/29530317/113964804-3f9ffd80-97fa-11eb-8f70-d4fd0e734731.png)

![image](https://user-images.githubusercontent.com/29530317/113964760-27c87980-97fa-11eb-9b94-a2685ed6ce0e.png)

**Comment by whittlem** [comment]
The sells happened because normal sell indicators were triggered. The "sellupperpcnt" is there to force a sell if no normal sell signal has been triggered but you want to lock in the sell anyway. It's difficult to tell what caused the sell from the output you provided alone. I would need the line below each of those to confirm.
