### ISSUE TITLE
Smart Switching

### ISSUE THREAD

**Issue by cbutler99** [whittlem/pycryptobot#337]
I have smart switching set to on

When it moves from 3600 to 900 it works however it does not seem to flip back to just 3600. I have to stop and restart the bot.

**Comment by whittlem** [comment]
It should swap back if the conditions are met. I'll check the code to make sure.

**Comment by ossedk** [comment]
I agree here, - something is not working. 

It does not switch back if you don't restart.

Temp solution is for me to make a restart every hour of the bot. Running a job doing this.

**Comment by whittlem** [comment]
I will fix it next.

**Comment by cbutler99** [comment]
Maybe unrelated but it seems that on the iterations the 6hr bar (coinbase) is not progressing. so at 15:00 it was still using the 06:00 bar from the 6hr timeframe whereas it should have progressed to the 12:00 bar. I will keep monitoring it. Only way to resolve was to stop and restart the bot.

**Comment by whittlem** [comment]
I've checked the code and the logic looks correct to me.

    if app.getSmartSwitch() == 1 and app.getGranularity() == 3600 and app.is1hEMA1226Bull() is True and app.is6hEMA1226Bull() is True:
        Logger.info('*** smart switch from granularity 3600 (1 hour) to 900 (15 min) ***')

        app.notifyTelegram(app.getMarket() + " smart switch from granularity 3600 (1 hour) to 900 (15 min)")

        app.setGranularity(900)
        list(map(s.cancel, s.queue))
        s.enter(5, 1, executeJob, (sc, app, state))

    if app.getSmartSwitch() == 1 and app.getGranularity() == 900 and app.is1hEMA1226Bull() is False and app.is6hEMA1226Bull() is False:
        Logger.info("*** smart switch from granularity 900 (15 min) to 3600 (1 hour) ***")

        app.notifyTelegram(app.getMarket() + " smart switch from granularity 900 (15 min) to 3600 (1 hour)")

        app.setGranularity(3600)
        list(map(s.cancel, s.queue))
        s.enter(5, 1, executeJob, (sc, app, state))

To switch from 1 hour to 15 minutes:
  - Granularity = 3600
  - EMA12 > EMA26 on 1 hour graph
  - EMA12 > EMA26 on 6 hour graph

To switch from 15 minutes to 1 hour:
  - Granularity = 900
  - EMA12 < EMA26 on 1 hour graph
  - EMA12 < EMA26 on 6 hour graph

If there really is a problem for sure then I agree with @cbutler99 it's most likely to be this:
app.is6hEMA1226Bull() 

Maybe there is a bug and it's always returning true. I'm going to investigate that function as the problem must be there.

**Comment by whittlem** [comment]
from models.PyCryptoBot import PyCryptoBot
  app = PyCryptoBot()
  print (app.is6hEMA1226Bull())

This is currently returning False. I'll take a look at the dataframe and see if there is anything suspicious in it.

**Comment by whittlem** [comment]
I think I found the problem. It's the caching for simulations.

**Comment by whittlem** [comment]
This should be fixed now. Please re-open if there is still a problem but should be working now.

**Comment by markhollingworth-worthit** [comment]
I found the same issue happening with binance for Simulations and Live operation.  I have done some investigation and I think I have found the reason for the Simulation not working correctly.

I have added some logging and it looks like the ema12 and ema26 data is not changing in the is6hEMA1226Bull(self) and the is1hEMA1226Bull(self) function it remains the same through the whole sim regardless of any buy signals.

I think whats happening is the df_data has a list of all the data covered by the test so in my test the data returned was from the 15-04-2021 up to 28-06-2021 and it looks like it is only using the last record so the 28-06 instead of picking the correct 6h  from the correct date.


With regards to Live the smartswitch not working, I changed the following lines locally and let it run overnight and the bot did smartswitch.

Change:
df_data = api.getHistoricalData
self.ema1226_6h_cache = df_data(self.market, '6h')

To:
df_data = api.getHistoricalData(self.market, '6h')
self.ema1226_6h_cache = df_data
