### ISSUE TITLE
[POSSIBLE BUG] Binance API Error

### ISSUE THREAD

**Issue by xgiovi9810x** [whittlem/pycryptobot#379]
![error](https://user-images.githubusercontent.com/39647283/124879532-9e2d7100-dfcd-11eb-81e1-ad21995bbe41.jpg)

So I'm doing some debug work on the bot (I'm testing a new strategy) and this night it gives me the error in the picture up here; I don't think it is a matter of my own code as I have just replaced the condition in the strategy.py file and more probably this was due to a server error from Binance (but still I think it should be handled without crashing). 
What do you think?

Note: The bot was running from 20:10 to 4:14 (UTC+2) that it the time when the exception happened

**Comment by ddemaio** [comment]
![Screen Shot 2021-07-10 at 5 53 47 PM](https://user-images.githubusercontent.com/8996626/125168882-f750fc80-e1a7-11eb-86b8-6154d5da397b.png)
I don't know if this is the result. Ever since the upgrade to the .key file, I've been unable to build the images from docker-compose up --build. It gives they errors. Part of me was thinking it's a mac not reading the key correctly, but one of the .py isn't reading the key.  Could be a binance api  error as that's what I am using.

**Comment by whittlem** [comment]
@letsautom8, can you help me with the Docker issue please? Seems having a separate .key file is causing issues with Docker. I read in the Telegram chat it may be due to a permission issue.

**Comment by whittlem** [comment]
@xgiovi9810x, is this a persistent issue or did it just happen once?

**Comment by ddemaio** [comment]
@whittlem at least for me using Docker, it started once on the update with moving the keys from the config. I haven't been able to get it to work with docker-compose up --build since that update. I believe it was the 2.45.0 update. It doesn't appear to be persistent. I know this is the case with both the coinbasepro and binance keys.

**Comment by xgiovi9810x** [comment]
@whittlem Nope but I didn't do a lot of real time test from that day.
