### ISSUE TITLE
Size is too accurate. Smallest unit is 1.00000000 - Coinbase

### ISSUE THREAD

**Issue by Sekuiya** [whittlem/pycryptobot#44]
I'm using your bot to trade XLM-EUR but it seems to be having trouble selling.
Besides that, it assumes the sell order was made successfully so it changes the "Last Action" to "SELL.
Here's a picture with the logs.
![totermw_ADX9q67yvT](https://user-images.githubusercontent.com/5737279/114699889-c41ddf00-9d18-11eb-8b03-a52c864934ba.png)

**Comment by whittlem** [comment]
Just an example of the exchanges making our lives difficult. It seems they want the order to be a whole number for Steller (XLM) specifically. 439 instead of 439.6107. I've not come across this before on Coinbase Pro and I've placed loads of XLM orders. I've had a lot of issues like this with Binance with all their rules. My Coinbase Pro orders have all been whole numbers, maybe just lucky. I know at least 5 others who are doing the same thing and they haven't had this issue. I'll add some code today to fix this for you. On the brighter side it looks like the bot would have sold at profit.
