### ISSUE TITLE
TrailingStopLossTrigger doesn't kick in at the correct margin

### ISSUE THREAD

**Issue by larcherMTT** [whittlem/pycryptobot#551]
**Describe the bug**
TrailingStopLossTrigger is not triggered at the margin specified by the config. 
By looking at Strategy.py seems that a trailing-stop-loss would occur if margin > self.app.trailingStopLossTrigger() this means that no sell for trailing-stop-loss will occour under trailingStopLossTrigger margin value, but the expected behaviour is that as soon as the margin overcome the trailingStopLossTrigger value it allows a sell for trailing-stop-loss even at lower margin. 

Example:
config:  trailingStopLossTrigger = 8 , TrailingStopLoss = 2

actual behaviour:
if margin reaches 9 and than fall back to 6 no sell for trailing-stop-loss will be triggered because when the margin loss 2% it is at 7% that is under the trailingStopLossTrigger margin value

**To Reproduce**
difficult to see in simulations

**Expected behavior**
if margin reaches 9 a sell signal would be triggered as soon as the margin drop by 2%

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I'm not 100% sure of the issue so I didn't raise a pull request.

proposed solution:
In strategy.py at line 236 should be 
and margin > self.app.trailingStopLossTrigger() - self.app.trailingStopLoss()
instead of 
and margin > self.app.trailingStopLossTrigger()

in this way as the margin hits trailingStopLossTrigger any drop of trailingStopLoss would trigger a sell.

**Comment by notoriousBLP** [comment]
I understood trailingstoploss and trigger to work exactly as you're describing. However, I think these numbers are more of an absolute value rather than relative to trigger in practice for this project. There is an image which is frequently used to convey the logic...it appears to be by design (although I am all for this method instead as it's the method I'm used to using and I think it results in more profit).


![sell_logic](https://user-images.githubusercontent.com/93151922/140188489-e3162706-3b71-4951-b18a-8fe5ae9067b4.jpg)

**Comment by larcherMTT** [comment]
Ok, I got it. Sorry for the raised issue, I was thinking at the trigger in a more literal way.
Btw congrats for the amazing project!

best regards, 
Matteo

--------------------------------------------------
Matteo Larcher
---------------------------------------------------
