### ISSUE TITLE
KeyError: "None of [Index(['currency', 'balance', 'hold', 'available'], dtype='object')] are in the [columns]"

### ISSUE THREAD

**Issue by Lineup2004** [whittlem/pycryptobot#660]
Hi
I have 2 markets running on a Raspberry Pi
Using % Docker ps tells me both containers are running, but one is restarting all the time.
Using % Docker-compose logs -f, it shows the KeyError. This happened after a reboot. At first both containers worked just fine.

Is there a way to reset this behaviour?

Many thanks for your help!
Kind regards,

**Comment by Lineup2004** [comment]
I've created 2 more containers, but they too have this KeyError.

**Comment by warrmr** [comment]
Sounds like you have a problem with your <exchange>.key file being created but not persisted for some reason. Are you using the old style config where you can put the API key and Seceret in the config.json and it auto generates the key file if so this is likely to be your problem. 

you will need to map your keyhole as a volume to a file outside of the container so that it persists. eg 

`-v ./binance.key:/app/binance.key` as part of your docker run command or follow the examples in the docker-compose setup with the volume mappings in the documentation. 

Change finance.key to the correct name for your configuration. 

If you need more assistance jump on the telegram chat and ask there as there are many people who can help. As this does not look like a bug and is more of a support request (I think)

**Comment by Lineup2004** [comment]
> Sounds like you have a problem with your .key file being created but not persisted for some reason. Are you using the old style config where you can put the API key and Seceret in the config.json and it auto generates the key file if so this is likely to be your problem.
> 
> you will need to map your keyhole as a volume to a file outside of the container so that it persists. eg
> 
> `-v ./binance.key:/app/binance.key` as part of your docker run command or follow the examples in the docker-compose setup with the volume mappings in the documentation.
> 
> Change finance.key to the correct name for your configuration.
> 
> If you need more assistance jump on the telegram chat and ask there as there are many people who can help. As this does not look like a bug and is more of a support request (I think)

@warrmr  That is great info! You are absolutely right! 
I forgot to add the volume mapping in the yaml file. So that's why the new style didn't work obviously.
I will give it a go.

Many thanks!!

**Comment by warrmr** [comment]
@Lineup2004 Did mapping the volume work in the end? if so would you mind just making a comment on this post with what you did and closing it as resolved if it is. 

Thanks :)
