### ISSUE TITLE
transition to coinbase from coinbasepro

### ISSUE THREAD

**Issue by DrBlackross** [whittlem/pycryptobot#729]
https://www.coinbase.com/advanced-trade

https://help.coinbase.com/en/coinbase/trading-and-funding/advanced-trade/what-is-advanced-trade

since transferring from coinbase to coinbasepro (deposits, etc....) are restricted to coinbase only. will the api setup have to change? like url, and im pretty sure ill need to generate a new api key pair.

**Comment by whittlem** [comment]
I am still using Coinbase Pro which works. I have no idea why Coinbase would promote Advanced Trade when it's not finished. They haven't even got the API working yet. When they get it working I will integrate it but just stick with Coinbase Pro for now.

**Comment by DrBlackross** [comment]
k

**Comment by snerdlock13** [comment]
Following the automatic transfer of my assets from Coinbase Pro to Coinbase a couple of months ago, I deleted my old Coinbase Pro API keys.  I have since generated new API keys from within Coinbase.  These API keys are paired with API secrets but not API passphrases.  I tried running pycryptobot using a 'coinbasepro.key' file containing one of these new API keys in the first line and its associated API secret in the second line (without any API passphrase in the third line) and using 'https://api.pro.coinbase.com' as the URL, but I receive the following error:
     TypeError: Coinbase Pro API key is invalid

If I understand pycryptobot correctly this is due to the API key I have provided not passing the API key syntax check within coinbase_pro_parser.py.  Is there an easy workaround?  Or, am I not able to use these new Coinbase API keys with the old Coinbase Pro API URL?

**Comment by whittlem** [comment]
I've just created a new API key for Coinbase Pro and it definitely still provides the passphrase. When you create an API key on Coinbase Pro you will see the passphrase on the first page, you will then get your secret, and if you look at the key created you will get the key. You should have three parts but make sure they have the correct permissions to be able to View and Trade.

I don't think there is anything wrong in the bot code as I use Coinbase Pro and it works fine for me. You must have an issue with generating your keys and adding it to the coinbasepro.key file.

**Comment by snerdlock13** [comment]
Thanks so much for the prompt reply.  Maybe I'm confused about something, are we able to use API keys generated on Coinbase Pro to authenticate requests to manage funds in a Coinbase (not Coinbase Pro) wallet?  Or do you mean you are still using the Coinbase Pro API to manage funds in your Coinbase Pro wallet?  Because the folks at Coinbase migrated my funds from my Coinbase Pro wallet to my regular Coinbase wallet, I assumed they had already taken Coinbase Pro offline.

**Comment by whittlem** [comment]
No, there are totally different. I have been looking at getting Coinbase Advanced Trade working but their API is not ready or not very good. I would use Coinbase Pro for the time being.
